name: Pack Launcher

on:
  push:
    paths:
      - 'update_all.sh'
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Pack Launcher
      run: ./.github/pack_launcher.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
